
## Last changed: 2023-10-16 17:16:33 UTC
version 14.1R4.8;
system {
    host-name vMX1;
    root-authentication {
        encrypted-password "$1$q8XvKcq.$.m0AZ/jXwEFV55sDDxh841";
    }
    login {
        user jcluster {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$1$kApZOJVa$UPA4mVJfP7XdhaAsQ033p0";
            }
        }
    }
    services {
        ssh {
            root-login allow;
        }
        netconf {
            ssh;
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.0.12.1/24;
            }
            family iso;
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.0.13.1/24;
            }
            family iso;
        }
    }
    em0 {
        unit 0 {
            family inet {
                address 10.0.0.191/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.1/32;
            }
            family iso {
                address 49.0001.0000.0000.0001.00;
            }
        }
    }
}
protocols {
    isis {
        level 1 disable;
        interface ge-0/0/0.0 {
            point-to-point;
        }
        interface ge-0/0/1.0 {
            point-to-point;
        }
        interface lo0.0 {
            passive;
        }
    }
}
